### PR TITLE
Generate types for darwin/arm64

### PR DESCRIPTION
**Pull request by paulcacheux**
Run `mktypes.sh` on darwin m1 (arm64)

### CODE REVIEW

**Review by KSerrania — APPROVED** [review]
LGTM, this fixes the full Datadog Agent build on macOS M1, which will allow us to remove the workaround we introduced here: https://github.com/DataDog/datadog-agent/pull/11683

**Comment by paulcacheux** [comment]
Maybe I should rebase the PR before merging

**Comment by KSerrania** [comment]
Yes, might be safer to rebase & regenerate the files given that this branch is a bit old just in case.

**Comment by paulcacheux** [comment]
Just repushed, can you test again, and I will merge

**Comment by KSerrania** [comment]
I got one error:
```
# github.com/DataDog/gopsutil/process
../../../../pkg/mod/github.com/!data!dog/gopsutil@v1.1.1-0.20220628122007-4a04e0832499/process/process_darwin.go:178:41: k.Eproc.Ucred.UID undefined (type Uucred has no field or method UID, but does have Uid)
../../../../pkg/mod/github.com/!data!dog/gopsutil@v1.1.1-0.20220628122007-4a04e0832499/process/process_darwin.go:576:43: k.Eproc.Ucred.UID undefined (type Uucred has no field or method UID, but does have Uid)
```

Upstream has `UID` instead of `Uid`: https://github.com/shirou/gopsutil/blob/7a094df3f7c9640d9f326410ebb0f8c34307a180/process/process_darwin_arm64.go#L95-L100

**Comment by paulcacheux** [comment]
Looking at it

**Comment by paulcacheux** [comment]
Can you try generating the amd64 code ? Re-running `mktypes.sh` I cannot manage to generate an upper-case `UID`

**Comment by KSerrania** [comment]
I tried regenerating the amd64 code here: https://github.com/DataDog/gopsutil/commit/efaf4c5a0b5d60b818d1202f8f6232258d7751be, there's a bunch of changes, including the `Uid` replacing `UID`. This seems to be a code generation issue, since `process_darwin.go` explicitly accesses `UID`: https://github.com/DataDog/gopsutil/blob/e8f965a9ab433b293cd03a8d901509ac0c694ef5/process/process_darwin.go#L178

**Comment by paulcacheux** [comment]
Looking at https://github.com/shirou/gopsutil/pull/917 they had to do it manually upstream :(

**Comment by paulcacheux** [comment]
So I will do it manually as well, and add a comment

**Comment by paulcacheux** [comment]
@KSerrania this should be good now

**Comment by KSerrania** [comment]
Works for me 👍, Alexandre and I have been able to compile the main Agent on amd64 and arm64 using your last commit.

**Pull request merged**
